# Generated by Django 4.1 on 2022-09-08 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_aboutmodel_alter_contactmodel_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactModel',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='message',
            new_name='text',
        ),
    ]
