# Generated by Django 4.1 on 2022-09-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_contactmodel_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='text',
            new_name='message',
        ),
    ]
