# Generated by Django 4.1 on 2022-09-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comment_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
